# Feature importance and model interpretation

This notebook is intentionally orchestration-only. Reusable importance functions live in `icare_risk.explainability`. Importance is calculated on the untouched temporal test set for interpretation. Feature selection for future parsimonious models must be performed using development data only.

In [15]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [16]:
from pathlib import Path
import joblib
import pandas as pd
import yaml
from IPython.display import display

from icare_risk.data.audit import load_admission_file
from icare_risk.models.training import encode_binary_target
from icare_risk.explainability import (
    model_coefficients,
    native_tree_importance,
    permutation_importance_table,
)

CONFIG_PATH = Path('../src/icare_risk/config/icare/analysis.yaml')
with CONFIG_PATH.open() as f:
    config = yaml.safe_load(f)

df = load_admission_file(config['outputs']['processed_dataset'])
target = config['columns']['target']
test = df.loc[df['split'].eq('test')].copy()
target_mapping = config.get('target_mapping', {})
test['__binary_target__'] = encode_binary_target(
    test[target],
    positive_values=target_mapping.get('positive_values'),
    negative_values=target_mapping.get('negative_values'),
)
test = test.dropna(subset=['__binary_target__'])
y_test = test['__binary_target__'].astype(int)
print(f'Test admissions with known outcomes: {len(test):,}')
print(f'Events: {y_test.sum():,}; event rate: {y_test.mean():.3f}')

Test admissions with known outcomes: 2,483
Events: 493; event rate: 0.199

In [17]:
model_directory = Path(config['outputs']['model_directory'])
fitted_models = {}
feature_map = {}
for model_cfg in config['models']:
    name = model_cfg['name']
    bundle = joblib.load(model_directory / f'{name}.joblib')
    fitted_models[name] = bundle['model']
    feature_map[name] = bundle['features']

available_models = list(fitted_models)
print('Available models:', available_models)

Available models: ['lr_kim_components', 'lr_all_score_values', 'lr_clinical_baseline', 'xgb_kim_components', 'xgb_all_score_values', 'xgb_clinical_baseline']

In [12]:
coefficient_tables = []
for name, model in fitted_models.items():
    if hasattr(model.named_steps.get('classifier'), 'coef_'):
        coefficient_tables.append(model_coefficients(model, model_name=name))

coefficients = (
    pd.concat(coefficient_tables, ignore_index=True)
    if coefficient_tables
    else pd.DataFrame()
)
display(coefficients.head(30))

,model,feature,coefficient,odds_ratio,absolute_coefficient
0,lr_kim_score,numeric__kim_hx_prior_esbl,-1.377807,0.252131,1.377807
1,lr_kim_score,numeric__kim_hx_prior_antibiotics_90d,-0.054253,0.947192,0.054253
2,lr_kim_score,numeric__kim_hx_recent_hosp_1yr,0.000000,1.000000,0.000000
3,lr_kim_score,numeric__kim_hx_nursing_home_resident,0.000000,1.000000,0.000000
4,lr_kim_score,numeric__kim_hx_urinary_catheter,0.000000,1.000000,0.000000
5,lr_all_scores,numeric__kim_score,-0.893678,0.409148,0.893678
6,lr_all_scores,numeric__tumbarello_score,0.400889,1.493152,0.400889
7,lr_all_scores,numeric__jones_score,0.044017,1.045000,0.044017
8,lr_all_scores,numeric__charlson_score,-0.021413,0.978815,0.021413
9,lr_all_scores,numeric__gavaghan_score,0.000000,1.000000,0.000000
10,lr_all_scores,numeric__holmgren_score,0.000000,1.000000,0.000000
11,lr_clinical_baseline,numeric__charlson_hx_leukemia,1.325629,3.764551,1.325629
12,lr_clinical_baseline,numeric__charlson_hx_diabetes_comp,-0.678224,0.507517,0.678224
13,lr_clinical_baseline,numeric__charlson_hx_cancer_solid,-0.475303,0.621697,0.475303
14,lr_clinical_baseline,numeric__charlson_hx_renal_mod_sev,-0.419171,0.657592,0.419171
15,lr_clinical_baseline,numeric__charlson_hx_stroke,0.392054,1.480017,0.392054
16,lr_clinical_baseline,numeric__charlson_hx_chf,-0.235002,0.790570,0.235002
17,lr_clinical_baseline,numeric__charlson_hx_liver_mild,-0.213952,0.807387,0.213952
18,lr_clinical_baseline,numeric__charlson_hx_pvd,0.199422,1.220697,0.199422
19,lr_clinical_baseline,categorical__INDEX_OF_MULTIPLE_DEPRIVATION_DEC...,0.138615,1.148682,0.138615
20,lr_clinical_baseline,categorical__GENDER_DESC_Unknown,-0.123903,0.883465,0.123903
21,lr_clinical_baseline,categorical__INDEX_OF_MULTIPLE_DEPRIVATION_DEC...,-0.118155,0.888558,0.118155
22,lr_clinical_baseline,categorical__INDEX_OF_MULTIPLE_DEPRIVATION_DEC...,-0.099168,0.905591,0.099168
23,lr_clinical_baseline,categorical__GENDER_DESC_Indeterminate,0.098154,1.103133,0.098154
24,lr_clinical_baseline,categorical__MAIN_SPECIALTY_CODE_DESC_general ...,-0.095504,0.908915,0.095504
25,lr_clinical_baseline,categorical__MAIN_SPECIALTY_CODE_DESC_oral sur...,0.081440,1.084848,0.081440
26,lr_clinical_baseline,categorical__INDEX_OF_MULTIPLE_DEPRIVATION_DEC...,0.079217,1.082440,0.079217
27,lr_clinical_baseline,categorical__GENDER_DESC_Female,0.063368,1.065419,0.063368
28,lr_clinical_baseline,numeric__charlson_hx_pulmonary,-0.062003,0.939880,0.062003
29,lr_clinical_baseline,categorical__INDEX_OF_MULTIPLE_DEPRIVATION_DEC...,-0.061477,0.940375,0.061477

In [13]:
permutation_tables = []
native_tables = []
n_repeats = config.get('explainability', {}).get('permutation_repeats', 20)

for name, model in fitted_models.items():
    features = feature_map[name]
    X_test = test[features]
    permutation_tables.append(
        permutation_importance_table(
            model, X_test, y_test, model_name=name,
            n_repeats=n_repeats,
        )
    )
    classifier = model.named_steps['classifier']
    if hasattr(classifier, 'feature_importances_'):
        native_tables.append(native_tree_importance(model, model_name=name))

permutation_importance = pd.concat(permutation_tables, ignore_index=True)
native_importance = (
    pd.concat(native_tables, ignore_index=True)
    if native_tables
    else pd.DataFrame()
)
display(permutation_importance.head(30))
if not native_importance.empty:
    display(native_importance.head(30))

,model,feature,importance_mean,importance_std,importance_rank
0,lr_kim_score,kim_hx_prior_esbl,0.001439,0.001114,1
1,lr_kim_score,kim_hx_recent_hosp_1yr,0.000000,0.000000,2
2,lr_kim_score,kim_hx_nursing_home_resident,0.000000,0.000000,3
3,lr_kim_score,kim_hx_urinary_catheter,0.000000,0.000000,4
4,lr_kim_score,kim_hx_prior_antibiotics_90d,-0.004498,0.006986,5
5,lr_all_scores,jones_score,0.002518,0.004153,1
6,lr_all_scores,gavaghan_score,0.000000,0.000000,2
7,lr_all_scores,holmgren_score,0.000000,0.000000,3
8,lr_all_scores,tumbarello_score,-0.000417,0.006210,4
9,lr_all_scores,kim_score,-0.006893,0.007284,5
10,lr_all_scores,charlson_score,-0.007938,0.011345,6
11,lr_clinical_baseline,MAIN_SPECIALTY_CODE_DESC,0.004840,0.007763,1
12,lr_clinical_baseline,GENDER_DESC,0.003824,0.006583,2
13,lr_clinical_baseline,INDEX_OF_MULTIPLE_DEPRIVATION_DECILE,0.003545,0.007612,3
14,lr_clinical_baseline,charlson_hx_liver_mild,0.002307,0.001155,4
15,lr_clinical_baseline,charlson_hx_diabetes_uncomp,0.001998,0.000853,5
16,lr_clinical_baseline,charlson_hx_stroke,0.001408,0.004167,6
17,lr_clinical_baseline,charlson_hx_chf,0.000711,0.002084,7
18,lr_clinical_baseline,charlson_hx_pvd,0.000579,0.000937,8
19,lr_clinical_baseline,charlson_hx_mi,0.000283,0.000433,9
20,lr_clinical_baseline,charlson_hx_cancer_solid,0.000074,0.000702,10
21,lr_clinical_baseline,charlson_hx_lymphoma,-0.000168,0.000041,11
22,lr_clinical_baseline,charlson_hx_leukemia,-0.000205,0.000560,12
23,lr_clinical_baseline,charlson_hx_pulmonary,-0.000760,0.000605,13
24,lr_clinical_baseline,charlson_hx_diabetes_comp,-0.001334,0.001192,14
25,lr_clinical_baseline,charlson_hx_renal_mod_sev,-0.001866,0.004699,15
26,lr_clinical_baseline,AGE_AT_ADMISSION,-0.002280,0.002663,16
27,xgb_kim_score,kim_hx_prior_esbl,0.001439,0.001114,1
28,xgb_kim_score,kim_hx_recent_hosp_1yr,0.000000,0.000000,2
29,xgb_kim_score,kim_hx_nursing_home_resident,0.000000,0.000000,3

,model,feature,importance,importance_rank
0,xgb_kim_score,numeric__kim_hx_prior_esbl,0.784268,1
1,xgb_kim_score,numeric__kim_hx_prior_antibiotics_90d,0.215732,2
2,xgb_kim_score,numeric__kim_hx_recent_hosp_1yr,0.000000,3
3,xgb_kim_score,numeric__kim_hx_nursing_home_resident,0.000000,4
4,xgb_kim_score,numeric__kim_hx_urinary_catheter,0.000000,5
5,xgb_all_scores,numeric__charlson_score,0.293471,1
6,xgb_all_scores,numeric__tumbarello_score,0.277425,2
7,xgb_all_scores,numeric__jones_score,0.225079,3
8,xgb_all_scores,numeric__kim_score,0.204026,4
9,xgb_all_scores,numeric__gavaghan_score,0.000000,5
10,xgb_all_scores,numeric__holmgren_score,0.000000,6
11,xgb_clinical_baseline,numeric__AGE_AT_ADMISSION,0.045503,1
12,xgb_clinical_baseline,categorical__INDEX_OF_MULTIPLE_DEPRIVATION_DEC...,0.042400,2
13,xgb_clinical_baseline,categorical__MAIN_SPECIALTY_CODE_DESC_general ...,0.042269,3
14,xgb_clinical_baseline,categorical__MAIN_SPECIALTY_CODE_DESC_oral sur...,0.041886,4
15,xgb_clinical_baseline,categorical__INDEX_OF_MULTIPLE_DEPRIVATION_DEC...,0.041560,5
16,xgb_clinical_baseline,categorical__INDEX_OF_MULTIPLE_DEPRIVATION_DEC...,0.040146,6
17,xgb_clinical_baseline,categorical__MAIN_SPECIALTY_CODE_DESC_gastroen...,0.039983,7
18,xgb_clinical_baseline,categorical__INDEX_OF_MULTIPLE_DEPRIVATION_DEC...,0.039852,8
19,xgb_clinical_baseline,categorical__INDEX_OF_MULTIPLE_DEPRIVATION_DEC...,0.038900,9
20,xgb_clinical_baseline,categorical__GENDER_DESC_Unknown,0.038589,10
21,xgb_clinical_baseline,categorical__INDEX_OF_MULTIPLE_DEPRIVATION_DEC...,0.038181,11
22,xgb_clinical_baseline,categorical__INDEX_OF_MULTIPLE_DEPRIVATION_DEC...,0.037983,12
23,xgb_clinical_baseline,categorical__INDEX_OF_MULTIPLE_DEPRIVATION_DEC...,0.037263,13
24,xgb_clinical_baseline,categorical__GENDER_DESC_Indeterminate,0.037004,14
25,xgb_clinical_baseline,categorical__GENDER_DESC_Female,0.036099,15
26,xgb_clinical_baseline,categorical__GENDER_DESC_Male,0.035761,16
27,xgb_clinical_baseline,numeric__charlson_hx_stroke,0.035299,17
28,xgb_clinical_baseline,categorical__INDEX_OF_MULTIPLE_DEPRIVATION_DEC...,0.035249,18
29,xgb_clinical_baseline,numeric__charlson_hx_diabetes_uncomp,0.035174,19

In [14]:
output_directory = Path(config['outputs'].get('feature_importance_directory', 'results/feature_importance'))
output_directory.mkdir(parents=True, exist_ok=True)
if not coefficients.empty:
    coefficients.to_csv(output_directory / 'logistic_regression_coefficients.csv', index=False)
permutation_importance.to_csv(output_directory / 'permutation_importance.csv', index=False)
if not native_importance.empty:
    native_importance.to_csv(output_directory / 'native_tree_importance.csv', index=False)
print(f'Saved feature-importance results to {output_directory}')

Saved feature-importance results to results/feature_importance